# -*- coding: utf-8 -*-
"""Pubmed-scraping-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBeM7Oh5mMs98tGC5cZfbbsYR2_MZqWT
"""

# !pip install biopython

from Bio import Entrez
import pandas as pd
import numpy as np
import math

Entrez.email = 'benedikt.vidic@gmx.de'

allIds = []

for x in range(0,21):
  year = 2013 + math.floor(x/2)
  startMonth = '01' if x%2 == 0 else '06'
  endMonth = '06' if x%2 == 0 else '12'

  handle = Entrez.esearch(db='pubmed',
  retstart=0,
  retmax='10000', #10000 ids per fetch is an api limit
  retmode='xml',
  mindate=str(year)+'/'+startMonth,
  maxdate=str(year)+'/'+endMonth,
  term='intelligence[Title/Abstract]')

  result = Entrez.read(handle)

  if len(result['IdList']) > 9000:
    print("A lot of articles in time section: ", x)
  allIds += result['IdList']


len(allIds)

